"""add task tables

Revision ID: 2f95c8d07362
Revises: e1c87cfd3575
Create Date: 2026-09-17 13:46:02.838430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f95c8d07362'
down_revision: Union[str, None] = 'e1c87cfd3575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parse_type', sa.Enum('PRODUCT_PAGE', 'SEARCH_QUERY', 'REVIEWS', 'CATEGORY', 'SELLER', name='parsetype'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'PAUSED', 'SUCCEEDED', 'FAILED', 'EXPIRED', 'CANCELLED', name='taskstatus'), server_default='QUEUED', nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('queue_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('result_limit', sa.Integer(), nullable=True),
    sa.Column('claimed_by', sa.String(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_reason', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('priority BETWEEN 1 AND 10', name='ck_tasks_priority_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('input_value', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'EXCLUDED', name='taskitemstatus'), server_default='PENDING', nullable=False),
    sa.Column('cursor', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'position', name='uq_task_items_task_position')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_items')
    op.drop_table('tasks')
    # ### end Alembic commands ###
    sa.Enum(name='parsetype').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='taskstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='taskitemstatus').drop(op.get_bind(), checkfirst=True)
