"""add audit_logs table

Revision ID: e1c87cfd3575
Revises: 589dc8c271ea
Create Date: 2026-09-17 11:12:51.255084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1c87cfd3575'
down_revision: Union[str, None] = '589dc8c271ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('AUTH_REGISTER_USER', 'AUTH_AUTHENTICATE_USER', name='auditaction'), nullable=False),
    sa.Column('action_type', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'AUTH', name='auditactiontype'), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILURE', name='auditstatus'), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('error_reason', sa.String(), nullable=True),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_logs')
    # `op.drop_table('audit_logs')` does not drop the native Postgres ENUM types backing
    # its enum columns — without this, a subsequent upgrade fails with
    # "type auditaction already exists" (and likewise for the other two).
    sa.Enum(name='auditaction').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='auditactiontype').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='auditstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
